### ISSUE TITLE
Add jumper for selecting external vs. default E-STOP and VDRIVE

### ISSUE THREAD

**Issue by npetersen2** [Severson-Group/AMDC-Hardware#102]
In the current REV D design, the PWM inverter interface will not function at all without wires plugged into the external screw connectors for `VDRIVE` and `ESTOP`.

Please add three-pin selectors for the following:

1. E-STOP: One position is external (functions like now), other position is enabled.
2. VDRIVE: One position is external (functions like now), other position is 5V.

**Comment by npetersen2** [comment]
Added jumper for VDRIVE input:

![image](https://user-images.githubusercontent.com/20168990/109107486-6ba66a00-76f7-11eb-81ad-fa50a46cd9cb.png)

Previously, VDRIVE connected straight to CON2 pin 1. Now, it goes through the header with the option of connecting board 5V directly, thus not needing to use the external pins.

**Comment by npetersen2** [comment]
## E-STOP

### Before:

![image](https://user-images.githubusercontent.com/20168990/109107635-b9bb6d80-76f7-11eb-9802-716e1720ce04.png)

### After:

![image](https://user-images.githubusercontent.com/20168990/109107817-0bfc8e80-76f8-11eb-823f-d8139472c389.png)

**Comment by GnomeTek** [comment]
Approved
