### ISSUE TITLE
isoSPI 24V power doesn't work

### ISSUE THREAD

**Issue by npetersen2** [Severson-Group/AMDC-Hardware#103]
The isoSPI connectors are supposed to have 24V power to supply the external circuitry if needed. Indeed, the `VIN2` signal is routed to pins at the connector, but there is an issue.

The `VIN2` is 24V, but in reference to the `VIN-` of the AMDC... NOT the common `GND`. This is due to the isolated DC/DC converters! Therefore, the 24V supply at the isoSPI connectors is NOT usable.

This may be okay since the 5V rail is still available for powering external boards.

![image](https://user-images.githubusercontent.com/20168990/77443669-3859ad80-6db9-11ea-930b-a885c737dff0.png)

**Comment by npetersen2** [comment]
Per planning meeting, this issue should be solved. We want 24V available for the expansion port.

To solve, I propose adding another small isolated DC/DC, probably 6W rated is fine; 24V at 250mA:
https://www.digikey.com/en/products/detail/cui-inc/PQQ6W-Q24-S24-S/13402043

This would add ~$10 to BOM and take up board space, but I think it is worth it and an easy solution.

**Comment by npetersen2** [comment]
Implemented:
1. Added 24V DC/DC to form isolated 24V rail
2. Used this new 24V rail for the GPIO port

![image](https://user-images.githubusercontent.com/20168990/109398211-0de56e00-7901-11eb-8427-aee9671b62b9.png)

**Comment by GnomeTek** [comment]
Approved
