### ISSUE TITLE
REV D BOM is missing standoffs and jumpers

### ISSUE THREAD

**Issue by elsevers** [Severson-Group/AMDC-Hardware#115]
The bill of materials is missing recommended:
1. standoffs (+ nuts) 
1. jumpers (but header pins are included)
1. Picozed connectors (`JX1`, `JX2`, `JX3`)
1. Picozed

**Comment by npetersen2** [comment]
@elsevers This issue already is documented here #97.

The PicoZed is not on the BOM since it cannot be bought from Digi-Key, while everything else can... I suppose another BOM file should be made for the different distribution companies (Digi-Key / Avnet)

**Comment by npetersen2** [comment]
Resolved via #97
