### ISSUE TITLE
Rename "isoSPI" ports to "GPIO" ports

### ISSUE THREAD

**Issue by npetersen2** [Severson-Group/AMDC-Hardware#140]
The `isoSPI` subsystem should be called `GPIO` since it contains both SPI and diff I/O signals... This will prevent confusion.

Rename the subsystem in the schematics and PCB silkscreen labeling.

**Comment by elsevers** [comment]
`GPIO` or `Expansion Port`?

**Comment by npetersen2** [comment]
Closed with #141
