### ISSUE TITLE
DAC board: fix ESD protection

### ISSUE THREAD

**Issue by mimayberry** [Severson-Group/AMDC-Hardware#146]
The TVS diodes used for ESD protection keep the DAC from outputting correct voltages  when ±7.5 V outputs are commanded on each set of four channels. 

The current TVS diode contains a center node, that allows for differential voltage to be applied the diodes. This leads to the diodes conducting and dropping the voltage at the DAC output. The current TVS diode looks like this:
<img width="282" alt="Screen Shot 2020-10-28 at 7 08 24 PM" src="https://user-images.githubusercontent.com/48141733/97510160-2b55fb80-1952-11eb-8b25-d5be3e42bfb4.png">

Solution is to use a TVS diode without the center node. Like this: 
<img width="176" alt="Screen Shot 2020-10-28 at 7 07 34 PM" src="https://user-images.githubusercontent.com/48141733/97510227-49236080-1952-11eb-9b12-60a1f7088fb0.png">

**Comment by npetersen2** [comment]
New part: https://www.digikey.com/en/products/detail/smc-diode-solutions/SMDA12CTR/6236252

**Comment by codecubepi** [comment]
@npetersen2 I saw that you merged DAC REV C into develop. Can we close this issue now as well, since it was addressed in REV C? The linked PR didn't seem to auto-close it.
