### ISSUE TITLE
Change shield termination 0R resistors to connect to VIN-, not the board GND layer

### ISSUE THREAD

**Issue by npetersen2** [Severson-Group/AMDC-Hardware#156]
Per discussion with @GnomeTek, we do not want the shield noise to be injected to the AMDC board common GND.

Instead, it should be shunted to the VIN ground. This can be accomplished by changing the connector termination resistors to connect to `VIN_GND` via a 1206 0R resistor and a thick trace width. Run the trace on the bottom layer and keep the resistors on the bottom layer as well.

Keep the default for these resistors as DNP.

**Comment by npetersen2** [comment]
Implemented:
- Switch to 1206 footprints for resistors
- Keep resistors as DNP
- Change resistor termination from `GND` to `GND_IN`

![image](https://user-images.githubusercontent.com/20168990/109398325-df1bc780-7901-11eb-924c-28d60b4ad5d2.png)

**Comment by GnomeTek** [comment]
With this being routed to the GND_In like you have now, I suggest placing the DNP as 0-Ohm so they are connected.

**Comment by npetersen2** [comment]
Updated all shield termination to be 0R by default, not DNP.

See 95d763e78095244112f9fd5328cd76a998e2168f
