### ISSUE TITLE
Merge BOM entry for duplicate part

### ISSUE THREAD

**Issue by npetersen2** [Severson-Group/AMDC-Hardware#159]
The REV D hardware BOM has the following entries:

![image](https://user-images.githubusercontent.com/20168990/107287768-04ff2c00-6a28-11eb-9c9e-fe8c41fd33e8.png)

Clearly, these are the same part and should be merged in the design... please do this to consolidate the BOM.

**Comment by npetersen2** [comment]
Replaced all U31 devices with `296-18593-1-ND`. This required rebuilding the `TranslationDir8Chan.SchDoc` sheet to be the same schematic symbol as the other part references.

**Comment by psinha25** [comment]
Looks good to me @npetersen2
