### ISSUE TITLE
Power Protection Circuit Modifications

### ISSUE THREAD

**Issue by GnomeTek** [Severson-Group/AMDC-Hardware#163]
These updates will allow proper operation of the input protection circuit. 

Update resistance values
- R83 - 0 Ohm/ Remove
- R55 - 390K ohm
- R58 - 4.12K ohm
- R59 - 5.9K ohm

Add filter capacitors (surface mount ceramic works fine)
- 56nF from OV pin to GND
- 56nF from UV pin to GND

Add pullup resistor from !FAULT to VIN for debugging. Fault is a pull down only. 
- 100K Ohm

**Comment by npetersen2** [comment]
Implemented the required changes. I used 100nF filter caps, hopefully that is ok, @GnomeTek?

![image](https://user-images.githubusercontent.com/20168990/109186591-b3101300-7756-11eb-93e4-20f83957e627.png)

@GnomeTek can you provide the equations you used to compute the resistor values? Or the script, etc. I would like to update the note in the schematics:

![image](https://user-images.githubusercontent.com/20168990/109186668-c9b66a00-7756-11eb-90a1-aedcd8075f27.png)

If at all possible, I would love construct the resistance values from just a few 10k and 100k P/Ns that are already in the BOM. Could do 2 10k in parallel to get ~5k. Then, 4 100k in series to get ~400k. Could replace the SHDN pullup with 2 100k. This would remove ~4 lines from the BOM! @GnomeTek thoughts?

**Comment by npetersen2** [comment]
Updated filter caps to 33nF per @GnomeTek comments.

**Comment by npetersen2** [comment]
Script from @GnomeTek for computing resistor values:

```MATLAB
clc;
close all;
clear all;
​
%% AMDC Curr Vals
R3 = 11.8e6;        % R55 & R83 = 5.9Meg each 11.8Meg 
R2 = 121e3;         % R58 = 121K
R1 = 178e3;         % R59 178K
%% Figure voltages from resistors
Iuv = 10e-9;        %abs minimum 10nA
Vos_UV = Iuv*(R1+R2);    % max tolerable offset of UV% 3mV
Ruv = Vos_UV/Iuv;
UVth = R3*.5/Ruv+.5;      % 20.232 v
OVth = 0.5*(Ruv+R3)/R1;     %33.986 v
​
%% Procedure for figuring resistors
Iuv = 10e-7;        % [A] abs minimum 10nA  % 1 pick bias current
Vos_UV = 10e-3;     % [V] choose UV offset tolerance
UVth = 20.;         % [V] Under voltage threshold
OVth = 34;          % [V] Over voltage threshold
Ruv = Vos_UV/Iuv;   
R3 = Ruv*(UVth - 0.5)/0.5;   % [Ohm]
R1 = ((Ruv+R3)/OVth)*0.5;    % [Ohm]
R2 = Ruv-R1;                 % [Ohm]
Itotal = OVth/(R3+R2+R1);    % [A]
P_R3 = Itotal^2*R3;          % [W]
P_R2 = Itotal^2*R2;          % [W]
P_R1 = Itotal^2*R1;          % [W]
```

**Comment by GnomeTek** [comment]
Approved!
