### ISSUE TITLE
Update top-level block diagram per latest I/O

### ISSUE THREAD

**Issue by npetersen2** [Severson-Group/AMDC-Hardware#164]
The `AMDC.SchDoc` sheet needs to be updated with pictures of latest connectors and correct I/O (i.e. merge UART and JTAG connectors per #158, etc)

![image](https://user-images.githubusercontent.com/20168990/109340970-52a0d480-782f-11eb-950c-b9a0759cdfa3.png)

**Comment by GnomeTek** [comment]
Approved!

**Comment by npetersen2** [comment]
Added `EEPROM` block to diagram to remind user this exists

![image](https://user-images.githubusercontent.com/20168990/112495796-36bb2080-8d52-11eb-9add-d397a2ce2709.png)
