### ISSUE TITLE
Add extra capacitor and pull-up resistor near the reset switch to reduce resetting due to ESD.

### ISSUE THREAD

**Issue by ASHAD1** [Severson-Group/AMDC-Hardware#165]
I would also prefer to have a TVS diode near the switch.
![image](https://user-images.githubusercontent.com/12862027/109720933-58b8ed00-7b70-11eb-8c2c-8079b025e128.png)

**Comment by GnomeTek** [comment]
Thinking about this, I think @ASHAD1 suggestion of having a TVS is a great idea, my comments were to be added along with that. 
In summary: 
TVS near the switch to inline resistor (10k? pick a nice common value you have) and the 100nF that is in place is adequate.

**Comment by npetersen2** [comment]
@ASHAD1 @GnomeTek I think I've added what you both have recommended:

Please review.

![image](https://user-images.githubusercontent.com/20168990/111404375-a79c7180-869c-11eb-8df2-23df7bab59e3.png)

**Comment by GnomeTek** [comment]
Best practice is to place TVS as close as possible to external source. So close to SW1, on the other side of R21.

In this configuration you can get carbonization (arcing) across the resistor reducing it's value. The ceramic capacitor could short in a severe over voltage situation.

**Comment by npetersen2** [comment]
Rearranged ordering of components per above comments.

See 332976bfcc88670f4fcbdf6df80678a233aa8aa7

![image](https://user-images.githubusercontent.com/20168990/112492738-84825980-8d4f-11eb-873c-348dae173c97.png)
