### ISSUE TITLE
Add local decoupling to the 2.048V analog reference voltage IC

### ISSUE THREAD

**Issue by npetersen2** [Severson-Group/AMDC-Hardware#170]
Even though the datasheet says it can operate without decoupling, add some caps to the input and output of the VREF device. 1uF should do for both.

Notice that the current design has no decoupling at the IC!

![image](https://user-images.githubusercontent.com/20168990/111093368-c0731e80-8506-11eb-9332-61dbc4c8cb8e.png)

**Comment by npetersen2** [comment]
Implemented using standard 1uF 0603 caps:

![image](https://user-images.githubusercontent.com/20168990/111093534-3081a480-8507-11eb-9cac-1c7fe45576f8.png)

**Comment by GnomeTek** [comment]
Approved!
