### ISSUE TITLE
Add local decoupling to VREF at diff amp ICs

### ISSUE THREAD

**Issue by npetersen2** [Severson-Group/AMDC-Hardware#171]
Looking at the layout... the VREF going to the Analog Signal Conditioning circuitry is only decoupled at the voltage reference IC itself. The signals then go a ways across the board before being used by the front-end circuitry.

Add some local decoupling to the VREF signals near the diff amps to help noise immunity since VREF is a constant value.

![image](https://user-images.githubusercontent.com/20168990/111094872-2f05ab80-850a-11eb-8292-505c8804b214.png)

**Comment by npetersen2** [comment]
Added one 0603 0.1uF cap for each diff amp:

![image](https://user-images.githubusercontent.com/20168990/111094931-53618800-850a-11eb-95c2-7fd758f088d5.png)

**Comment by npetersen2** [comment]
Very hard to see, but I placed these caps physically close to the diff amp ICs:

![image](https://user-images.githubusercontent.com/20168990/111095539-a2f48380-850b-11eb-9632-d7a6378f3472.png)

**Comment by GnomeTek** [comment]
Approved!
