### ISSUE TITLE
Add website to PCB layout

### ISSUE THREAD

**Issue by npetersen2** [Severson-Group/AMDC-Hardware#173]
I think it should be in the silkscreen, near the main "AMDC" feature.

Planning on doing: `www.amdc.dev`

Could also entertain `www.github.com/Severson-Group/AMDC-Hardware` but I think this is a bit long and verbose.

**Comment by elsevers** [comment]
Good idea. go for `amdc.dev` (I think we can omit the `www.` to keep it short).

**Comment by npetersen2** [comment]
Added to layout:

![image](https://user-images.githubusercontent.com/20168990/112494549-25254900-8d51-11eb-91eb-4aed0cf89b02.png)
