### ISSUE TITLE
Silicon Serial Number for Revision identification

### ISSUE THREAD

**Issue by jjsylvestre** [Severson-Group/AMDC-Hardware#18]
https://pdfserv.maximintegrated.com/en/ds/DS2401.pdf

**Comment by npetersen2** [comment]
@elsevers What's the purpose of this? It wouldn't be hard to add (just one IC plus a few caps), but not sure about requirements. Is this still needed/wanted?

**Comment by npetersen2** [comment]
Not implemented on REV C board. Need more information about this.

**Comment by npetersen2** [comment]
This seems like a dead issue. @elsevers feel free to reopen this if this is actually needed. Otherwise, I'll just ignore it.
