### ISSUE TITLE
Change SCREW1..13 P/N in BOM and Altium

### ISSUE THREAD

**Issue by npetersen2** [Severson-Group/AMDC-Hardware#189]
Per a mix up with REV E assembly, change the P/N for SCREW1..13 to be: `36-9900-ND`

**Comment by npetersen2** [comment]
Confirmed that REV F changes in PR #228 resolved this issue.

**Comment by codecubepi** [comment]
![image](https://github.com/Severson-Group/AMDC-Hardware/assets/63322525/aaa148fc-425d-4fa0-9238-795510fd70e3)

Approved! It looks like all screws have the correct supplier part number.

**Comment by npetersen2** [comment]
Closing since this was resolved in the REV F hardware
