### ISSUE TITLE
uInverter:Change DC link resistor part no. in BOM sheet

### ISSUE THREAD

**Issue by purohitparth25** [Severson-Group/AMDC-Hardware#194]
Part number (541-RCS06032K49FKEACT-ND) listed in BOM sheet for a 2.49 K Ohm resistor, however, the resistor in the schematic is a 2.2 K Ohm. Part number in the BOM needs to be updated.

![image](https://user-images.githubusercontent.com/90465550/153779174-16d92542-8237-4b6d-8522-bb9d61ce84c0.png)

**Comment by npetersen2** [comment]
For reference, this is the voltage divider resistors for the DC bus sensing:

![image](https://user-images.githubusercontent.com/20168990/154088958-76e9685c-188f-4441-a9d5-425235ee8281.png)

this would explain the gain seen for the voltage feedback not being what was expected per the schematic values... :)
