### ISSUE TITLE
AMDC: Fix footprint TSOP65P640X120-16N for AM26C32 Sig-Diff

### ISSUE THREAD

**Issue by codecubepi** [Severson-Group/AMDC-Hardware#211]
While working on the DAC Board Rev C, I found that the footprint for the AM26C32 (TSOP65P640X120-16N in PcbLib) did not pass the DRC. Two issues:

- The outline silkscreen was too close to the pads. Move the outline X to +/- 1.6mm.

- The Solder Mask Expansion on the pads was too wide. Set Solder Mask Expansion on all pads to Manual, 0.04mm.

**Comment by npetersen2** [comment]
Thanks @codecubepi for flagging this! We'll keep this on the back burner for the next version of the AMDC hardware

**Comment by codecubepi** [comment]
Approved!

**Comment by npetersen2** [comment]
Closing since this was resolved in the REV F hardware
