### ISSUE TITLE
IC Failure Issue: AMDC Rev E, AM26C31 transciever on expansion port failure

### ISSUE THREAD

**Issue by Zhouzhou377** [Severson-Group/AMDC-Hardware#215]
## Problem
Two AMDC users have reported a failure with the AM26C31 IC, the differential output transceiver that drives the four expansion ports. In both cases:
- U46 failed
- The board connected to the expansion port was a [REV B Kaman IO Converter Board](https://github.com/Severson-Group/AMDC-Hardware/tree/develop/Accessories/Kaman_IO_ConverterBoard/REV20210414B). 

One user also reported that their Kaman IO Converter Board stopped working at the same time that this IC failed.

One user replaced U46 in their AMDC and the expansion port began working again.

## Possible Cause
Note that the Kaman IO Converter Board Rev B does not provide any termination resistor for the differential signal: 
![image](https://user-images.githubusercontent.com/7421348/190512260-b96cf8f8-a2c1-47ff-bf3b-923c67faddfb.png)
The data sheet for the receiver part indicates that a termination resistor should be provided. 

Upon inspection with an oscilloscope, large voltage overshoots are observed at the AM26C31 pins. We are speculating that the AM26C31 part may have become damaged by voltage reflections from the non-terminated expansion board.

**Comment by npetersen2** [comment]
The Kaman expander board was updated in REV C (https://github.com/Severson-Group/AMDC-Hardware/pull/225) to include the termination resistors discussed in this issue.

Per the new REV C Kaman board updates, I am marking this issue as "solved" and closing it.
