### ISSUE TITLE
Kaman I/O Board: Add diff I/O termination resistors

### ISSUE THREAD

**Issue by npetersen2** [Severson-Group/AMDC-Hardware#218]
## Issue Description

The I/O between the AMDC and the Kaman adapter board is differential. However, there is no termination resistors on the signals, either on the AMDC or the Kaman adapter board. This causes ringing and voltage overshoots. The datasheet highly recommends a termination resistor of 80-120 ohms.

## Changes Requested

Add four termination resistors to the Kaman adapter board design. Attach between the `_P` and `_N` signals:

![image](https://user-images.githubusercontent.com/20168990/191041329-2fd1b3ff-49fc-4fc2-9016-f925d44e3fe8.png)

## Hardware Testing Results

Here are a few scope captures of the original board with no termination resistors, and then with added termination resistors of ~120 ohms. All captures are the raw diff I/O, so you will see a nominal polarity and the negated polarity.

In the captures below, `C8` is always the filtered `CNV_n` signal to the Kaman sensors. The `CNV_n` falling edge triggers the ADC sampling.

### 1. `CNV_n` signal

![gpio2--00002](https://user-images.githubusercontent.com/20168990/191042407-dcb99e4e-47c6-4a5e-b436-fed684b0717a.png)

![gpio2--00003](https://user-images.githubusercontent.com/20168990/191042464-27114161-9c38-43bd-9026-39541ebf5a09.png)

### 2. `SCK` signal

![gpio2--00000](https://user-images.githubusercontent.com/20168990/191042549-2c81ee4f-1d92-42ec-9dee-1434b867aafc.png)

![gpio2--00001](https://user-images.githubusercontent.com/20168990/191042559-3f7733c1-f3fe-49a7-8a6f-899cfb51d3be.png)

### 3. `CNV_n` signal, with termination resistor

![gpio2--00014](https://user-images.githubusercontent.com/20168990/191042937-3ad24dd7-9527-46bd-a149-5c2328bcfa81.png)

![gpio2--00015](https://user-images.githubusercontent.com/20168990/191042955-5c88f621-5764-4f15-88b5-35ff5487c999.png)

### 4. `SCK` signal, with termination resistor

![gpio2--00012](https://user-images.githubusercontent.com/20168990/191042822-6b841439-1a0e-4525-bd21-10e3b85fc187.png)

![gpio2--00013](https://user-images.githubusercontent.com/20168990/191042833-14348588-2f09-4706-b1e5-cc4f3749347f.png)

**Comment by elsevers** [comment]
Thanks @npetersen2. I am noticing that the voltage levels in these signals appear to be at ~3.3V level. I am confused by this because the transceivers on both the AMDC (i.e. U46) and the adapter board are at 5V. Shouldn't we expect to see these signals go between 0V and 5V?

![image](https://user-images.githubusercontent.com/7421348/213185432-ced0ad8f-cbf7-450b-afd4-e116c96eafab.png)
![image](https://user-images.githubusercontent.com/7421348/213185503-197f8f71-9309-4bc3-ab9f-d651ef17ac58.png)
