### ISSUE TITLE
Kaman I/O Board: failed Schmitt trigger IC used for glitch filter

### ISSUE THREAD

**Issue by npetersen2** [Severson-Group/AMDC-Hardware#219]
## Description

On one of the Kaman adapter boards in the lab, I found that the second stage Schmitt trigger IC had failed.

Adding this issue so others have an idea of what to look for, should they run into issues.

## Hardware Waveforms

The glitch filter on the Kaman adapter board is composed of two Schmitt triggers and two RC LPFs. The filters help remove high frequency glitches and the Schmitt triggers convert the "soft" filtered waveform back to being a sharp square wave.

The waveforms below are captured on a board where the RC LPFs were altered to be `R = 10 kOhm` and `C = 1 pF` for both filters. This results in a higher bandwidth for the second filter.

I scoped the signal chain for the `SCK` line with no external noise (i.e. no DC link PWM switching)

### 1. Input from diff I/O receiver

![gpio2--00016](https://user-images.githubusercontent.com/20168990/191045197-10551edd-61ec-4172-b83f-d2debfdcbf88.png)

### 2. First RC filter output

![gpio2--00017](https://user-images.githubusercontent.com/20168990/191045248-8f71e879-bcf8-49f5-9e9a-54d5e0b05276.png)

### 3. Output of 1st Schmitt trigger

![gpio2--00018](https://user-images.githubusercontent.com/20168990/191045538-820d9e75-b0a7-4741-bbef-0ba74c76e077.png)

### 4. Second RC filter output

![gpio2--00019](https://user-images.githubusercontent.com/20168990/191045594-336c805d-ba83-48c5-9778-f57dd6982c9d.png)

### 5. Output of 2nd Schmitt trigger

![gpio2--00020](https://user-images.githubusercontent.com/20168990/191045659-0055f97a-6e18-46a7-892a-744c2011239c.png)

**Notice the bad waveform from the second Schmitt trigger!!**

It appears the output stage low-side driver is damaged--there are sharp rising edges, but "RC" falling edges.

After replacing the 2nd Schmitt trigger with a different IC, the output became square wave again.

**Comment by codecubepi** [comment]
I am experiencing a similar issue, my second Schmitt trigger IC seems to be faulty and lose the SCLK line entirely

#### Input to first Schmitt Trigger

![pat4](https://github.com/Severson-Group/AMDC-Hardware/assets/63322525/c05ad7e5-11d1-4926-8427-4bbe9c16e0c5)

#### Output of second Schmitt Trigger 

![pat3](https://github.com/Severson-Group/AMDC-Hardware/assets/63322525/bd63975c-1735-4559-885d-1b799c160f0e)

**Comment by codecubepi** [comment]
@npetersen2 

Did we forget to close this at the end of last year?

I believe this should've been closed by [307](https://github.com/Severson-Group/AMDC-Firmware/pull/307) in the AMDC-Firmware repo.

**Comment by npetersen2** [comment]
@codecubepi I am trying to remember what this issue is...

How does the firmware updates fix the hardware issue? I think this is related to a termination resistor (?)

**Comment by codecubepi** [comment]
@npetersen2 

I think there were two related hardware issues here:

1. The trigger ICs used on that board occasionally go faulty, which we just just fixed by replacing them (I know I had to replace the IC at least once). I think that was the issue you encountered, which I guess would not be fixed by firmware, only be replacing the part.
2. The issue I mentioned was that the filtering was too aggressive for the higher SCLK frequencies we were running at in May. We fixed that by changing the RC values on the REV C Kaman Adapter board, and then making the filter delay configurable in the firmware.

I guess I don't know enough about point 1, your original problem. Maybe this _isn't_ fully closed, but I had the tab open still so I figured I would check.

**Comment by npetersen2** [comment]
@codecubepi thanks.

Let's close this issue for now and re-open or create a new one if/when someone runs into a similar issue down the road.

**Comment by elsevers** [comment]
@anirudhupadhyaya has created issue #231 which seems to be documenting the same problem. He addressed it by soldering in new components. You'll notice in the pictures of his adapters board that he has a large number of fly wires soldered in. The current theory is that these wires picked up ESD which damaged the Schmitt triggers. At this point, we aren't planning any design changes in response.
