### ISSUE TITLE
U3B and U7 failure in Kaman adapter board during testing

### ISSUE THREAD

**Issue by anirudhupadhyaya** [Severson-Group/AMDC-Hardware#231]
# Context

In the ARL project for BP4 drive, we are using two Kaman eddy current sensors. During Anirudh's testing one of the Kaman demodulator boxes got  damaged, more details on this in Severson-Group/ARL-eturbo#37. When trying to re-configure the eddy current sensors it was found that the two Kaman adapter boards had also suffered some damage. It is unclear the sequence of events or cause/ effect relationship right now.

# Details

## Board 1
Schmitt trigger IC U3B was found to be damaged. Hence the SCLK and CNV signals to the demodulator is not correct, so no data is received.

![IMG_0852](https://github.com/Severson-Group/AMDC-Hardware/assets/90214161/41ec6135-6c38-4f17-bed0-7735c6e1d856)

### Scope captures

I and @npetersen2 probed the CNV and SCLK signals at three locations marked 1,2 and 3. The signals at 1 and 2 look as expected while the signals at 3 at the output of U3B does not look good.

_**SCLK at 1**_

This is the clock signal from AMDC after level shifting. CLK frequency - 2000 kHz. Looks good.

![aux4](https://github.com/Severson-Group/AMDC-Hardware/assets/90214161/ae372544-98a1-4eda-8b5e-e399a850e5a4)

_**SCLK at 2**_

This should be inverted of 1 and thats what we see.

![aux5](https://github.com/Severson-Group/AMDC-Hardware/assets/90214161/2ed23613-bcba-4c04-8151-6e4a6a6d14c8). 

_**SCLK at 3**_

This signal is not as expected. Does not look like a good CLK signal.
![aux6](https://github.com/Severson-Group/AMDC-Hardware/assets/90214161/e9886439-29e7-4b86-998d-3c3ae997789f)

_**CNV at 1**_
Looks good.
![aux7](https://github.com/Severson-Group/AMDC-Hardware/assets/90214161/3b0c7e80-ea1e-4da0-a3a0-d7d60ca72c2f)

_**CNV at _2_**_
Should be inverted from 1. Looks good.
![aux8](https://github.com/Severson-Group/AMDC-Hardware/assets/90214161/5be72daa-1cae-4549-998d-ea7aaed73b04)

**_CNV at 3_**

Not looking good here. RC behavior seen, instead of a square pulse.

![aux9](https://github.com/Severson-Group/AMDC-Hardware/assets/90214161/2915b6ba-b713-4bf5-aaf5-d40bc691a48c)

## Board 2

In this board we found that IC U7 was damaged. This is responsible for level shifting the SCLK and CNV signals from the AMDC. 
![IMG_0854](https://github.com/Severson-Group/AMDC-Hardware/assets/90214161/1c26dcef-0e77-4b65-93a7-4072001eed3d) 

### Scope capture
SCLK signal at output of U7. Not looking good. This is not as expected, hence led us to the conclusion that U7 is damaged.

![aux10](https://github.com/Severson-Group/AMDC-Hardware/assets/90214161/6ed1b35d-a8ad-43e2-bf86-d390140f8245)

### Additional point
However, Anirudh found that after fixing this part the board was not working as expected. Further debugging revealed that U3B also to be damaged like board 1.

**Comment by elsevers** [comment]
**Outcome:** @anirudhupadhyaya was able to repair both boards and them working for his purposes by replacing the components described above.

@anirudhupadhyaya or @npetersen2, can one of you leave a comment on if this issue should motivate any changes to the adapter board design?

**Comment by anirudhupadhyaya** [comment]
Per my understanding here, U3A and U3B (second schmitt trigger IC) have been damaged on several boards during testing apart from this instance.. There could be some benefit to investigating this failure further and identifying a better IC

**Comment by elsevers** [comment]
#218 documents the same problem and was closed due to us having insufficient evidence that any board/part changes are necessary. 

I think that @anirudhupadhyaya's issue here also does not add sufficient evidence to make a design change. You'll notice in the pictures above that one of the boards has a large number of fly wires soldered in. The current theory is that these wires picked up ESD which damaged the Schmitt triggers.

Other potentially related issues: #218 and #226
