### ISSUE TITLE
TestBoard: find alternative part for BNC connector

### ISSUE THREAD

**Issue by npetersen2** [Severson-Group/AMDC-Hardware#236]
The BNC connector (https://www.digikey.com/en/products/detail/te-connectivity-amp-connectors/5-1634503-1/1755969) in the BOM for the AMDC TestBoard is obsolete. We need to find a replacement.

It should be footprint compatible with the existing part.

@codecubepi when you get a chance, can you please look for one and post a reply to this issue with suitable options?

**Comment by codecubepi** [comment]
@npetersen2 

## *Original Part:* TE Connectivity 5-1634503-1 [DigiKey](https://www.digikey.com/en/products/detail/te-connectivity-amp-connectors/5-1634503-1/1755969) [Mfg](https://www.te.com/usa-en/product-5-1634503-1.html)

![image](https://github.com/Severson-Group/AMDC-Hardware/assets/63322525/d0f5128d-bdd8-4f3f-928d-1dc495b1e2b0)

- [x] Height from PCB 13.7mm

## *DigiKey Recommended Alternate:* Amphenol 112404 [DigiKey](https://www.digikey.com/en/products/detail/amphenol-rf/112404/1011728) 

![image](https://github.com/Severson-Group/AMDC-Hardware/assets/63322525/ff74cd2e-dfdb-4e29-92f6-e8e93b297be7)

- [x] Should be *close enough* to be footprint-compatible
- [x] Height from PCB also 13.7mm 
- [x] DigiKey lists same key specs: 50 ohm impedance, 4 GHz max freq, 500 V
- [x] DigiKey In-Stock (and Normally Stocking), Unit Price 3.68 USD

## *TE Conn. Recommended Replacement*: TE Connectivity 5413969-2 [DigiKey](https://www.digikey.com/en/products/detail/te-connectivity-amp-connectors/5413969-2/2188140) [Mfg](https://www.te.com/usa-en/product-5413969-2.html)

![image](https://github.com/Severson-Group/AMDC-Hardware/assets/63322525/fdd2460f-6ffa-46bf-bff2-0c27116a5ff2)

![image](https://github.com/Severson-Group/AMDC-Hardware/assets/63322525/49801c7b-b04d-4eb9-912a-e4c80f5d7bd2)

- [ ] This is not even as close as the Amphenol above to being footprint-compatible
- [ ] The connector height is also much taller, 20.57mm from PCB
- [x] Same key specs: 50 ohm impedance, 4 GHz max freq, 500 V
- [x] DigiKey In-Stock (and Normally Stocking), Unit Price 5.02 USD

## *My Alternate Pick*: Cinch Connectivity VB335 [DigiKey](https://www.digikey.com/en/products/detail/cinch-connectivity-solutions/VB335/4430332)

![image](https://github.com/Severson-Group/AMDC-Hardware/assets/63322525/8ecfd188-c7b3-4915-b64a-b9c4dddf1cd1)

- [x] Close enough to be footprint-compatible
- [ ] Height from PCB 18.7mm
- [x] Same key specs
- [x] DigiKey In-Stock (and Normally Stocking), Unit Price 4.14 USD

**Comment by codecubepi** [comment]
If I were to choose from those three alternates, I'd probably go with the Amphenol alternate recommended by DigiKey.

**Comment by npetersen2** [comment]
Thanks @codecubepi !! I'll make a PR to update the BOM and tag you for review
