### ISSUE TITLE
Fix component values for Power Protection circuitry

### ISSUE THREAD

**Issue by npetersen2** [Severson-Group/AMDC-Hardware#50]
On REV B and now REV C boards, we have simply shorted out the power protection circuitry to disable it because the specified resistor values don't seem to work.

It would be nice to have this added protection working for us, so we need to figure out what the values should be and update the schematics.

**Comment by npetersen2** [comment]
@ASHAD1 Can you take a look at the datasheet for LTC4365 and give calculating resistor values a go? I want a second set of eyes on this since it isn't exactly trivial and I want it to work for REV D... :) Perhaps deadline by middle of week of so?

![image](https://user-images.githubusercontent.com/20168990/70400615-c7ed7300-19f9-11ea-9fae-a37cb7d4f4d4.png)

**Comment by ASHAD1** [comment]
@npetersen2 I have looked into the datasheet, The value calculated was the same (R1 = 176.5k, R2 = 123.5k, R3 = 11.7M). We can have a working range very close to 20V -34V.
For shutdown resistor (R55) we can use a resistor in the range of 100k - 500k. Higher value, if we expect to have some transients.

**Comment by npetersen2** [comment]
@ASHAD1 great thanks for the feedback. I have picked available resistors and updated design, see below. I have also removed the fault LED indicator -- during a fault, we don't have reliable power to power the LED... so no point in having a LED there! Does the schematic look good to you?

![image](https://user-images.githubusercontent.com/20168990/70866555-35892a00-1f39-11ea-8bdf-456822a11e90.png)
