### ISSUE TITLE
Update Inrush Current Limiter circuitry

### ISSUE THREAD

**Issue by npetersen2** [Severson-Group/AMDC-Hardware#52]
The calculated value for C48 was too small and still resulted in the hiccuping issue.

I stacked a 100nF cap on top of C48 on the REV C board and it fixed the issue.

We probably don't need to increase C48 all the way up to 100nF from 100pF, but it does work...

Let's update the schematics to reflect this needed change.

![image](https://user-images.githubusercontent.com/20168990/49831985-fb4fe000-fd5a-11e8-9b60-872b03307c7e.png)

**Comment by elsevers** [comment]
If the datasheet of this part requests a 100pF capacitor for reasons of ESR, etc., we may consider placing a 100 nF capacitor in parallel with the 100pF capacitor.

**Comment by npetersen2** [comment]
Done.
