### ISSUE TITLE
Changes to PowerStack I/O cable

### ISSUE THREAD

**Issue by elsevers** [Severson-Group/AMDC-Hardware#78]
-Merge VDD / VIO to PowerStack: support 3.3V and 5V.
- Keep VDRIVE terminal connection as is
-Per discussion, add separate PSSUPPLY terminal that goes directly to DB15 connections. Each DB15 should have a high current 0 ohm resistor to let user select if power to powerstack comes from AMDC or not.

**Comment by npetersen2** [comment]
Done.
