### ISSUE TITLE
Adding over-voltage protection to the ADC input pins

### ISSUE THREAD

**Issue by ASHAD1** [Severson-Group/AMDC-Hardware#83]
ADC inputs are connected to op-amp which has a bias voltage of +15V and -15V, but the ADC inputs are rated for 8Vp-p.

**Comment by npetersen2** [comment]
@ASHAD1 Do you have a part number recommendation on this? preferably something small, not BGA :)

**Comment by npetersen2** [comment]
@ASHAD1 With new input protection (+/-19V), do we still need this?

**Comment by ASHAD1** [comment]
@npetersen2  this protection should be fine. I also recommend changing the the Op-amp supply to single rail 0-5V.

**Comment by elsevers** [comment]
If we implement #88, I think we can close this.

**Comment by npetersen2** [comment]
Closed per #88 fixes.
