### ISSUE TITLE
Verify voltage rating of ADC protection

### ISSUE THREAD

**Issue by elsevers** [Severson-Group/AMDC-Hardware#89]
Verify that the +- 12V ADC input rating is compatible with:
- Kaman eddy current sensors (check part Nick just purchased as well as DIT 5200N)
- Current/voltage sensor board design

**Comment by mimayberry** [comment]
The voltage output of the DIT 5200N is specified as +- 10V typical and the KD-2306 (Nick's) is
0-10V standard. The +-12V rating should be good for these sensors.

However the sensor boards are capable of outputting +-15V, therefore we may consider upgrading the TVS diode from the `SMDA12CTR` to the `SMDA15CTR` which has a reverse standoff of 15V. The reverse standoff voltage of a TVS should always be at or above the operating range of input circuitry.
